// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FT3.Migrations
{
    [DbContext(typeof(WorkoutContext))]
    [Migration("20180827203027_seedexerciseType")]
    partial class seedexerciseType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FT3.Models.Exercise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Max");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("Exercise");

                    b.HasData(
                        new { ID = 357, Max = 205, Name = "Bench Press" },
                        new { ID = 358, Max = 305, Name = "Squat" },
                        new { ID = 359, Max = 325, Name = "Deadlift" }
                    );
                });

            modelBuilder.Entity("FT3.Models.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExID");

                    b.HasKey("ID");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("FT3.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Reps");

                    b.Property<int?>("SessionID");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("SessionID");

                    b.ToTable("Set");
                });

            modelBuilder.Entity("FT3.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("Date");

                    b.Property<int>("DistanceInMeters");

                    b.Property<long>("TimeInSeconds");

                    b.HasKey("Id");

                    b.ToTable("Workout");
                });

            modelBuilder.Entity("FT3.Models.Set", b =>
                {
                    b.HasOne("FT3.Models.Session")
                        .WithMany("Sets")
                        .HasForeignKey("SessionID");
                });
#pragma warning restore 612, 618
        }
    }
}
