// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FT3.Migrations
{
    [DbContext(typeof(WorkoutContext))]
    partial class WorkoutContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FT3.Models.Exercise", b =>
                {
                    b.Property<int>("exerciseID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("exerciseMax");

                    b.Property<string>("exerciseName");

                    b.Property<string>("exerciseType");

                    b.HasKey("exerciseID");

                    b.ToTable("Exercise");

                    b.HasData(
                        new { exerciseID = 357, exerciseMax = 205, exerciseName = "Bench Press", exerciseType = "Strength" },
                        new { exerciseID = 358, exerciseMax = 305, exerciseName = "Squat", exerciseType = "Strength" },
                        new { exerciseID = 359, exerciseMax = 325, exerciseName = "Deadlift", exerciseType = "Strength" }
                    );
                });

            modelBuilder.Entity("FT3.Models.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExID");

                    b.HasKey("ID");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("FT3.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Reps");

                    b.Property<int?>("SessionID");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("SessionID");

                    b.ToTable("Set");
                });

            modelBuilder.Entity("FT3.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("Date");

                    b.Property<int>("DistanceInMeters");

                    b.Property<long>("TimeInSeconds");

                    b.HasKey("Id");

                    b.ToTable("Workout");
                });

            modelBuilder.Entity("FT3.Models.Set", b =>
                {
                    b.HasOne("FT3.Models.Session")
                        .WithMany("Sets")
                        .HasForeignKey("SessionID");
                });
#pragma warning restore 612, 618
        }
    }
}
